<?xml version="1.0"?>

<robot
    xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
    xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
    xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface">
    
    <!-- Properties (Constants) -->
    <property name="M_PI" value="3.14159"/>
    
    <property name="wheel_offset_z" value="${-base_size_z/2 + 0.0236}" />
    
    <macro name="erratic_wheel" params="suffix parent reflect">
        <joint name="${parent}_${suffix}_wheel_joint" type="continuous">
            <origin xyz="0.075 ${reflect*0.165} -0.0539" rpy="0 0 0" />
            <axis xyz="0 1 0" />
            <anchor xyz="0 0 0" />
            <limit effort="100" velocity="100" />
            <joint_properties damping="0.0" friction="0.0" />
            <parent link="${parent}" />
            <child link="${parent}_${suffix}_wheel_link" />
        </joint>
        
        <link name="${parent}_${suffix}_wheel_link">
            <inertial>
                <mass value="0.1" />
                <origin xyz=" 0 0 0 " />
                <inertia  ixx="0.012411765597" ixy="0.0" ixz="0.0"
                          iyy="0.015218160428" iyz="0.0"
                          izz="0.011763977943" />
            </inertial>
            
            <visual>
                <origin xyz="0 0 0" rpy="0 0 ${M_PI/2}" />
                <geometry>
                    <mesh filename="package://erratic_description/meshes/erratic_wheel.stl"/>
                </geometry>
                <material name="Black" />
            </visual>
            
            <collision>
                <origin xyz="0 0 0" rpy="0 0 ${M_PI/2}" />
                <geometry>
                    <mesh filename="package://erratic_description/meshes/erratic_wheel.stl"/>
                </geometry>
            </collision>
        </link>

        <gazebo reference="${parent}_${suffix}_wheel_link" >
            <mu1 value="100.0" />
            <mu2 value="100.0" />
            <kp  value="1000000.0" />
            <kd  value="1.0" />
            <material>Erratic/Grey</material>
        </gazebo>

        <gazebo reference="${parent}_${suffix}_motor_link" >
            <material>Erratic/White</material>
        </gazebo>

        <transmission type="pr2_mechanism_model/SimpleTransmission" name="${parent}_${suffix}_wheel_trans">
            <actuator name="${parent}_${suffix}_wheel_motor" />
            <joint name="${parent}_${suffix}_wheel_joint" />
            <mechanicalReduction>1.0</mechanicalReduction>
        </transmission>
    </macro>
</robot>

